BM-9 Comments Create & Destroy, UI Fixes/Changes
umair-khalid-brainx/brainx-media pull request #5
Opened 2022-12-06 09:04 UTC by umair-khalid-brainx

2022-12-08 15:42 UTC, usama-javaid-brainx requested changes

2022-12-08 15:42 UTC, usama-javaid-brainx commented on Gemfile
> +gem "image_processing"
why have you changed gem version?

2022-12-08 15:42 UTC, usama-javaid-brainx commented on app/controllers/comments_controller.rb
> +    @post = @user.posts.find(params[:post_id])
you should show flash messages for every action in all controllers

2022-12-08 15:42 UTC, usama-javaid-brainx commented on config/application.rb
> +    config.time_zone = 'Karachi'
why we need to set time zone here?

2022-12-08 15:42 UTC, usama-javaid-brainx commented on app/views/posts/index.html.erb
> +              <% end %>
you must try to use eager loading here

2022-12-09 05:44 UTC, umair-khalid-brainx commented on config/application.rb
> +    config.time_zone = 'Karachi'
Time in my Rails app is 5 hours behind local, changing time solved nothing.

2022-12-09 07:52 UTC, umair-khalid-brainx commented on app/controllers/comments_controller.rb
> +    @post = @user.posts.find(params[:post_id])
facing some issues showing notices with turbo

2022-12-14 11:50 UTC, merged